### ISSUE TITLE
Code inside bullet list without fences always dedented

### ISSUE THREAD

**Issue by tkruse** [wooorm/mdast#76] opened 2015-09-28 10:43 UTC
mdast will change this (one blank line):
```
* List

        8-space Indented Code
```

but accept this (two blank lines):
```
* List


        8-space Indented Code
```
I believe one blank line should be suffcient:
http://meta.stackexchange.com/questions/3792/how-to-nest-code-within-a-list-using-markdown

**Comment by wooorm** [comment] 2015-09-28 10:50
What version of mdast are you on, and what settings do you use?

When fiddling with the [demo](http://mdast.js.org/demo/?text=*%20List%0A%0A%20%20%20%20%20%20%20%208-space%20Indented%20Code%0A) I see the correct output (one empty line) on all settings (except for pedantic, which you probably won’t want to use!)

**Comment by tkruse** [comment] 2015-09-28 12:25
Sorry, I am using mdast 2.0.0, my settings were:
```
{
  "settings": {
    "pedantic": true,
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }
}
```

I confirm turning pedantic off does not show that symptom. So close if that makes the issue invalid.

**Comment by wooorm** [comment] 2015-09-28 12:38
@tkruse Thanks! However, I still cannot reproduce how the example you gave me produces different markdown output?

Could it be that you either need more code to get this issue to show up, or, that you’re using CRLF as line-endings?

![screen shot 2015-09-28 at 2 33 33 p m](https://cloud.githubusercontent.com/assets/944406/10135477/8d47a81a-65ee-11e5-831b-858cc950de7e.png)

**Comment by tkruse** [comment] 2015-09-28 12:42
Sorry again. I wrote based on assumptions. My complete .mdastrc is:
```
{
  "plugins": {
    "lint": {
        "unordered-list-marker-style": "consistent",
        "list-item-bullet-indent": false,
        "list-item-indent": false,
        "no-missing-blank-lines": false,
        "no-html": false,
        "maximum-line-length": false,
        "no-file-name-mixed-case": false,
        "no-multiple-toplevel-headings": false,
        "maximum-line-length": 79,
        "emphasis-marker": "*",
        "no-tabs": false,
        "blockquote-indentation": false,
        "strong-marker": "*"
    }
  },
  "settings": {
    "pedantic": true,
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }

}
```

**Comment by tkruse** [comment] 2015-09-28 12:43
without the lint plugin, even with pedantic, the symptom does not show. I did not know the lint plugin affects the output.

**Comment by wooorm** [comment] 2015-09-28 12:43
@tkruse Really? It shouldn’t :astonished:

**Comment by tkruse** [comment] 2015-09-28 12:46
Using mdast-lint 1.1.1

**Comment by wooorm** [comment] 2015-09-28 12:51
Still cannot reproduce :o.

Could you (in a new directory):

1. Create an `example.md` file, with the following content (with a EOF newline):

    ```
    * List

            8-space Indented Code
    ```

2. Create an `.mdastrc` file:

    ```
    {
      "plugins": {
        "lint": {
          "unordered-list-marker-style": "consistent",
          "list-item-bullet-indent": false,
          "list-item-indent": false,
          "no-missing-blank-lines": false,
          "no-html": false,
          "maximum-line-length": false,
          "no-file-name-mixed-case": false,
          "no-multiple-toplevel-headings": false,
          "maximum-line-length": 79,
          "emphasis-marker": "*",
          "no-tabs": false,
          "blockquote-indentation": false,
          "strong-marker": "*"
        }
      },
      "settings": {
        "pedantic": true,
        "bullet": "*",
        "listItemIndent": "1",
        "strong": "*",
        "emphasis": "*"
      }
    }
    ```

3. `npm install mdast mdast-lint -g`;

4. `DEBUG="*" mdast example.md`?

5.  Show its output here?

**Comment by tkruse** [comment] 2015-09-28 12:57
Really weird...
```
$ mdast --version
2.0.0
$ echo $'* List\n\n        8-space indented code' > example.md  
$ cat example.md
* List

        8-space indented code

$ cat .mdastrc                    
{
  "plugins": {
    "lint": {
        "unordered-list-marker-style": "consistent",
        "list-item-bullet-indent": false,
        "list-item-indent": false,
        "no-missing-blank-lines": false,
        "no-html": false,
        "maximum-line-length": false,
        "no-file-name-mixed-case": false,
        "no-multiple-toplevel-headings": false,
        "maximum-line-length": 79,
        "emphasis-marker": "*",
        "no-tabs": false,
        "blockquote-indentation": false,
        "strong-marker": "*"
    }
  },
  "settings": {
    "pedantic": true,
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }

}
$ mdast  example.md --no-color -q 
* List

      8-space indented code


example.md
        3:5  warning  Error: Don’t use mixed indentation for children, remove 2 spaces
    at VFile.message (/home/kruset/.nvm/v0.11.10/lib/node_modules/mdast/node_modules/vfile/index.js:372:11)
    at VFile.warn (/home/kruset/.nvm/v0.11.10/lib/node_modules/mdast/node_modules/vfile/index.js:409:28)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/lib/rules/list-item-content-indent.js:94:22
    at Array.forEach (native)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/lib/rules/list-item-content-indent.js:51:23
    at one (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:96:22)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:83:29
    at forwards (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:24:13)
    at all (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:82:16)
    at one (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:100:20)  list-item-content-indent

⚠ 1 warning
```

**Comment by wooorm** [comment] 2015-09-28 12:59
@tkruse That’s looks good right?

Could it be that the input file had CRLF instead of LF line-endings?

**Comment by tkruse** [comment] 2015-09-28 13:26
No, it does not look good. There should be no warning, and the output markup should still have 8 char indent. It only has 6.

**Comment by wooorm** [comment] 2015-09-28 13:31
Oh sorry, missed that. Was checking the double newline you mentioned in your first post.

Could you run `DEBUG="*" mdast example.md`?

**Comment by tkruse** [comment] 2015-09-28 13:34
Result:
```
$ DEBUG="*" mdast example.md
  mdast:cli:ignore Constructing ignore for `/home/kruset/work/markdown/CppCoreGuidelines` +0ms
  mdast:cli:traverse Checking `example.md` +5ms
  mdast:cli:file-set-pipeline:stdin Checking stdin +1ms
  mdast:cli:file-set-pipeline:stdin Ignoring stdin +0ms
  mdast:cli:file-pipeline:read Reading `example.md` in `utf-8` +0ms
  mdast:cli:file-pipeline:read Read `example.md` (err: null) +2ms
  mdast:cli:configuration Constructing configuration for `example.md` +0ms
  mdast:cli:configuration Using /home/kruset/work/markdown/CppCoreGuidelines/.mdastrc +1ms
  mdast:cli:file-pipeline:configure Setting output `undefined` +2ms
  mdast:cli:file-pipeline:configure Using settings `{"position":true,"gfm":true,"yaml":true,"commonmark":false,"footnotes":false,"pedantic":true,"breaks":false,"entities":"false","setext":false,"closeAtx":false,"looseTable":false,"spacedTable":true,"incrementListMarker":true,"fences":false,"fence":"`","bullet":"*","listItemIndent":"1","rule":"*","ruleSpaces":true,"ruleRepetition":3,"strong":"*","emphasis":"*"}` +0ms
  mdast:cli:file-pipeline:configure Using plug-ins `["lint"]` +0ms
  mdast:cli:file-pipeline:configure Using plug-in `lint` at `/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint` +0ms                                                                                                                                     
  mdast:cli:file-pipeline:configure Applying options `{"unordered-list-marker-style":"consistent","list-item-bullet-indent":false,"list-item-indent":false,"no-missing-blank-lines":false,"no-html":false,"maximum-line-length":79,"no-file-name-mixed-case":false,"no-multiple-toplevel-headings":false,"emphasis-marker":"*","no-tabs":false,"blockquote-indentation":false,"strong-marker":"*"}` to `lint` +35ms                                                                                                                                     
  mdast:cli:file-pipeline:parse Parsing document +2ms
  mdast:cli:file-pipeline:parse Parsed document +13ms
  mdast:cli:file-pipeline:transform Transforming document +1ms example.md
  mdast:cli:file-pipeline:transform Transformed document (error: null) +7ms
  mdast:cli:file-pipeline:queue Queueing example.md +0ms
  mdast:cli:file-pipeline:queue Can flush for `example.md` +1ms
  mdast:cli:file-pipeline:queue Flushing +0ms
  mdast:cli:file-pipeline:stringify Compiling document +0ms
  mdast:cli:file-pipeline:stringify Compiled document to md +1ms
  mdast:cli:file-pipeline:copy Not copying +0ms
  mdast:cli:file-pipeline:stdout Writing document to standard out +0ms
* List

      8-space indented code

  mdast:cli:file-pipeline:file-system Ignoring writing to file-system +1ms

example.md
        3:5  warning  Error: Don’t use mixed indentation for children, remove 2 spaces
    at VFile.message (/home/kruset/.nvm/v0.11.10/lib/node_modules/mdast/node_modules/vfile/index.js:372:11)
    at VFile.warn (/home/kruset/.nvm/v0.11.10/lib/node_modules/mdast/node_modules/vfile/index.js:409:28)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/lib/rules/list-item-content-indent.js:94:22
    at Array.forEach (native)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/lib/rules/list-item-content-indent.js:51:23
    at one (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:96:22)
    at /home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:83:29
    at forwards (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:24:13)
    at all (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:82:16)
    at one (/home/kruset/work/markdown/CppCoreGuidelines/node_modules/mdast-lint/node_modules/unist-util-visit/index.js:100:20)  list-item-content-indent

⚠ 1 warning

```

**Comment by wooorm** [comment] 2015-09-28 13:54
Oh, sorry, I completely misread your question!

I though that mdast changed your first code-example to your second. Now I understand what you’re referring to: mdast changes the first example to `6` spaces, but doesn’t for he second example.

The reason for the first, is that in pedantic mode, up-to four spaces are eaten from every line. In other modes, up to the size of the initial indent (thus `* ` = 2) is removed. To cater for other algorithms (e.g., [commonmark](http://spec.commonmark.org/dingus/?text=*%20List%0A%0A%20%20%20%20%20%20%20%208-space%20indented%20code%0A)), stringification adds only four spaces before code.

Otherwise, the code would have more indentation than needed,

The warning is there because lint detects the difference: the paragraph is indented by two, the code by eight characters.

the difference between your first and your second example is that the second is parsed as a list with a single item, followed by a code block, with in it [four more spaces](http://spec.commonmark.org/dingus/?text=*%20List%0A%0A%0A%20%20%20%20%20%20%20%208-space%20Indented%20Code%0A).

So, to conclude, this is a feature rather than a bug: this allows “legacy” markdown to be portable to more “modern” formats. If you don’t agree, please re-open this issue or create a different one.

**Comment by tkruse** [comment] 2015-09-28 14:12
Well, the first thing is, this only happens when the lint plugin is activated (and pedantic). Just pedantic does not change the line. So there should be a bug somewhere, I believe.

Next, with pedantic and lint, 8-space indent is reduce to 6-space, 6-space is reduce to 4-space, and 4-space to 2-space:
```
kruset:arkdown/example $ cat example.md
* List

        8-space indented code

* List

      6-space indented code

* List

    4-space indented code

   @ krulap2 : /home/kruset/work/markdown/example  
* List

      8-space indented code

* List

    6-space indented code

* List

  4-space indented code
```

So mdast output is something that when running mdast again, will again be fixed. That cannot be right, I believe.

I cannot reopen this issue on github (not sure why).

**Comment by wooorm** [comment] 2015-09-28 14:25
Darn, you’re right: `mdast example.md > example-2.md && mdast example-2.md > example-3.md && mdast example-3.md > example-4.md && mdast example-4.md > example-5.md` does indeed produce smaller and smaller (till `2`) indents. That is indeed a bug, and should be fixed.

However, that still happened without the `lint` plugin so I don’t think that can be it.

**Comment by tkruse** [comment] 2015-09-28 14:38
Ahhhh, sorry. I never cross-checked the new output with the lint warning message. I assumed they would always come together. Sorry for the confusion.

So I agree, what I said earlier was wrong. This happens always for pedantic, and is a bug because it always produces smaller indents.
Whether 8 or 6 should be right I am not sure, But I believe even with pedantic, 8 should be right. But I don't know much about the different markdown flavors, so 6 might be right.

**Comment by tkruse** [comment] 2015-09-28 14:41
BTW: Is it possible to get the lint output without the whole stacktrace? -q does not seem to change much for me.

**Comment by wooorm** [comment] 2015-09-28 14:44
The stack trace is on lower node versions (just checked), I didn’t get it on 4.0.0, `nvm install 4.0.0; nvm alias default 4.0.0; nvm use default` should fix it perfectly permanently :wink:

If you feel like it you can additionally open an issue on `vfile-reporter` (I’d be very happy, just quite busy atm)

**Comment by tkruse** [comment] 2015-09-28 14:52
4.0.0 works for me.

**Comment by wooorm** [comment] 2015-09-28 14:59
:+1:

**Comment by wooorm** [comment] 2015-10-02 15:33
@tkruse Ah, this was a hard one, but I’ve figured it out!

As mentioned [earlier](https://github.com/wooorm/mdast/issues/76#issuecomment-143758778), I though this was a bug. But today I did some tests and came to the conclusion that mdast is doing *exactly what you want it to*. Namely, read input as pedantic, and compile the list-item (with `listItemIndent: 1`) to 6 spaces.

I think the “listItemIndent: mixed” and “listItemIndent: 1” are not compatible with pedantic list-items. And we can either disable one of the options (not transparent) or throw an error.

An alternative would be to always ensure `8` spaces are used in code-blocks inside list-items, but that would result in other parsers seeing code with some extra spaces inside it (e.g., white-space will be rendered at the start of HTML code-blocks, before the code). I don’t think that would be smart, compatibility wise.

**Comment by tkruse** [comment] 2015-10-02 15:50
throwing an error would be fine with me, for incompatibilities

**Closed** 2015-10-02 19:53 UTC

**Comment by wooorm** [comment] 2015-10-02 19:55
This should be smart enough to not throw when this cade doesn’t occur. However, this can only detect when mdast is used normally (through `#process(value, options)`), and not for example when just compiling using `#stringify(value, options)`, as `pedantic` is a parse setting and `listItemIndent` a compile setting.

Thanks for the time on this issue. Please let me know if you find more of these discrepancies!
